name: steviepontour
favicon: null
layout_spectrum: 0.8372552969958633
typography_spectrum: 0.09343885071575642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4719024582300335
  lightness: 0.9325157704297453
  saturation: 0.8936618259176612
  rhythmicContrast: 0.13656919682398438
purpose: []
