name: steviepontour
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2782
title: 'The adventures of a little known musician with a thirst to soak up all the fun & change the world at the same time.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#04a3e0'
    - '#c3e9f7'
    - '#82d0ef'
    - '#28ace3'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
